### ISSUE TITLE
Is there a way to completely disable Pushy for a device by calling a single method?

### ISSUE THREAD

**Issue by zvonedev** [pushy/pushy-sdk-ios#10]
Hi, I'm looking for a way to disable Pushy and Push notifications programmatically through the App. 

For Android, I found:

 `Pushy.toggleNotifications(Boolean enabled, Context ctx);`

Is there something like this for iOS? I found:

`Pushy.toggleAPNs( _value: Bool) `

but it seems to not work. I have tried calling toggleAPNs with both True and False value, but I receive the same results.

Tested on 1.0.38 Pushy version, iOS 16

**Comment by pushy** [comment]
Hi @zvonedev,
Thanks for your patience. This has now been resolved in https://github.com/pushy/pushy-sdk-ios/commit/045c7b62e5d93ac6658d211bfe934e788c448199 with the addition of `pushy.unregister()`. 

Invoking this new method will unregister the device from remote notifications. Calling `pushy.register()` on this device in the future will restore the device token which was previously assigned to the device, and make it possible to receive notifications again.

1) Import version `1.0.39` of the Pushy iOS SDK by updating the import statement in your project's `Podfile` within the `target` declaration:
```
pod 'Pushy', '1.0.39'
```

2) Save the file and run the following command to install the SDK:

```
pod install
```

3) Call `pushy.unregister()` from your app code to unregister the device. Please make sure not to call `pushy.register()` until you're ready for the device to receive notifications again:

```
// Unregister from push notifications
pushy.unregister()
```

Please let us know if you face any issues.
