### ISSUE TITLE
How to hide a specific notification banner when application is in killed state

### ISSUE THREAD

**Issue by kumarlav0** [pushy/pushy-sdk-ios#12]
In my project Pushy used to handle Firebase push notification. Now a requirement is that. Not to show notification banner when Application is in killed state or application is in background state.

- I am able to handle this when application is in foreground. 

```
func notificationWillPresent(userInfo: [String: Any], completionHandler: ((UNNotificationPresentationOptions) -> Void)?) {
 let remoteNotification = RemoteNotificationModel(userInfo)
completionHandler?([.sound])
}
```
But I want this same when app is in background or in killed state.

**Comment by pushy** [comment]
Hi @kumarlav0,
Thanks for reaching out. We'd be glad to assist.

Unfortunately, it is **not possible** to execute custom code in the background (for example, to update local SQLite data) **without** displaying a notification when your app is in the background/killed state on iOS. 

As per the Apple docs:

> Notification service app extensions only operate on remote notifications configured in the system to **display an alert** to the user. If alerts are disabled for your app, or if the payload specifies only the playing of a sound or the badging of an icon, the extension isn’t employed.

However, you can use the `content_available: true` flag to specify that the notification should be a silent one (no visible alert but you can still execute code). It won't be delivered when the app is killed, but it will be delivered if the app is running in the background/foreground. In that case, you can check the app background/foreground state and act accordingly to display a notification or not within your `Pushy.setNotificationHandler()`:

```
let state = UIApplication.shared.applicationState
if state == .background || state == .inactive {
    // background
} else if state == .active {
    // foreground, generate a local notification
}
```

This requires the **Background Modes -> Remote Notifications** capability to be enabled.

Please let us know if there's anything else we can help with.
