### ISSUE TITLE
How to update local sqlite data from custom data of Push notification payload when application is in Killed state or in background state

### ISSUE THREAD

**Issue by kumarlav0** [pushy/pushy-sdk-ios#13]
In my project [Pushy](https://github.com/pushy/pushy-sdk-ios) used to handle Push notification. I want to update my local Sqlite data when I got a specific type of Push Notification.

I am able to handle this when application is in foreground. Using this Delegate method.

```
func notificationWillPresent(userInfo: [String: Any], completionHandler: ((UNNotificationPresentationOptions) -> Void)?) {
 let remoteNotification = RemoteNotificationModel(userInfo)
completionHandler?([.sound])
}
```
But I want this same local data updating when app is in background or in killed state. Could you please suggest me how I can Achieve this.

I did a lot of R & D and found that no method calls when app is in killed state or in background state to handle this.

**Comment by pushy** [comment]
Hi @kumarlav0,
Thanks for reaching out. We'd be glad to assist.

It is possible to execute custom code when notifications are received in the background / killed state by implementing a [Notification Service Extension](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension) along with specifying the `mutable_content: true` flag:
```
{
    "to": "a6345d0278adc55d3474f5",
    "data": {
        "message": "Hello World!"
    },
    "mutable_content": true,
    "notification": {
        "title": "Test Notification",
        "body": "Hello World \u270c",
        "badge": 1,
        "sound": "ping.aiff"
    }
}
```

Your app's Notification Service Extension will be invoked even if the app is running in the background, making it possible to execute code before the notification is displayed. This requires the **Background Modes -> Remote Notifications** capability to be enabled.

Please refer to the Apple docs for help on implementing a Notification Service Extension:
https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications/

**Comment by kumarlav0** [comment]
Thank you. Will try the same. If I get any issue will connect you again.
