### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by andryg98** [pushy/pushy-sdk-ios#15]
Hello,
could you please provide a privacy manifest as requested by Apple?

There are API usages that need to be addressed in the manifest file. For example, NSUserDefaults.

Thank you

Apple: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by pushy** [comment]
Hi @andryg98,
Thanks so much for bringing this to our attention.

We've just added an Apple Privacy Manifest in https://github.com/pushy/pushy-sdk-ios/commit/6684535d9777c9bb374ef1cf80b6f7640849118f and https://github.com/pushy/pushy-sdk-ios/commit/db3d11f8c0a14a700a588bd2ea252fd519b1a1c6 and released version `1.0.53` of the Pushy iOS SDK.

Please import version `1.0.53` of the SDK by updating the version in the following statement of your project's `Podfile` within the `target` declaration:

```
pod 'Pushy', '1.0.53'
```

Save the file and run the following command to install the SDK:

```
pod install --repo-update
````

Please let us know if you have any questions or face any issues.
