### ISSUE TITLE
App crash on setting pushy.setCustomNotificationOptions

### ISSUE THREAD

**Issue by mohitk196** [pushy/pushy-sdk-ios#16]
Code: 
```
let pushy = Pushy(UIApplication.shared)

pushy.setCustomNotificationOptions([UNAuthorizationOptions.badge, UNAuthorizationOptions.alert, UNAuthorizationOptions.sound])
```

> Could not cast value of type 'Swift.Array<__C.UNAuthorizationOptions>' (0x1edab38e0) to '__C.UNAuthorizationOptions' (0x104194b60).

<img width="871" alt="Screenshot 2024-04-17 at 12 04 08 AM" src="https://github.com/pushy/pushy-sdk-ios/assets/56431665/9cc8cfee-c26c-4666-be32-d4586fb86d01">

**Comment by pushy** [comment]
Hi @mohitAppRinger,
Thanks for reaching out. We'd be glad to assist.

The default notification authorization options are already set to `[.badge, .alert, .sound]` so there is no need to explicitly call `pushy.setCustomNotificationOptions()` unless you are wishing to add an additional option such as `.criticalAlert`.

If you still wish to call the method, please declare the first parameter in a variable first, and proceed to call the method as follows:
```
if #available(iOS 12, *) {
   let options: UNAuthorizationOptions = [.badge, .alert, .sound, .criticalAlert]
   pushy.setCustomNotificationOptions(options)
}
```

Please give it a try, and let us know if you face any issues.
