### ISSUE TITLE
It's possible to get into inconsistent state with no way to recover

### ISSUE THREAD

**Issue by nikolaykasyanov** [pushy/pushy-sdk-ios#2]
As far as I can see Pushy saves both Pushy and APNS tokens into Keychain and user defaults upon registering.

The problem is if for whatever reason no APNS token is saved to keychain but a Pushy token is saved and app is then removed & installed wiping user defaults, the Pushy token will still be there but not the APNS token, meaning [the code](https://github.com/pushy-me/pushy-sdk-ios/blob/master/PushySDK/Pushy.swift#L131-L144) in `Pushy.registerPushyDevice(apnsToken:)` will always fail without any recovery option except removing Pushy token from keyhcain programmatically. It means that for end users it's essentially an irrecoverable state.

**Comment by pushy** [comment]
Hi @nikolaykasyanov,
Thanks so much for your report.

The SDK saves all 3 items to the Keychain at once:
https://github.com/pushy-me/pushy-sdk-ios/blob/b1e644b61db5d407c4699518232b1aa2f3224afc/PushySDK/Pushy.swift#L196-L198

Therefore, how did you reach a situation where only the Pushy device token is saved to Keychain and not the APNs token?

**Comment by nikolaykasyanov** [comment]
@pushy-me honestly I don't know but this happened. Anyway, keychain doesn't guarantee atomicity when three items are saved in a row, any (or all) of those 3 can fail leading to inconsistent state.

**Comment by pushy** [comment]
Thanks @nikolaykasyanov, we've addressed this scenario in https://github.com/pushy-me/pushy-sdk-ios/commit/62137d6003cdb2aa174e3e3cde373f00426a1d0e and released version `1.0.21`:
https://pushy.me/docs/ios/get-sdk

Thanks again 🎉

**Comment by nikolaykasyanov** [comment]
@pushy-me thank you very much, appreciate the quick reaction.
